name: Static Checks
on: [push, pull_request]


jobs:
  static-check-clang-format:
    runs-on: "ubuntu-20.04"
    name: Static checks (clang-format)
    steps:
    - name: checkout-gdsdecomp
      uses: actions/checkout@v2
      with:
      # get all history
        fetch-depth: 0
    # Azure repositories are not reliable, we need to prevent azure giving us packages.
    - name: Install Linux deps
      if: matrix.platform == 'linux'
      run: |
        sudo rm -f /etc/apt/sources.list.d/*
        sudo cp -f misc/ci/sources.list /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install clang-format-6.0
    - name: check clang_format
      run: bash ./.scripts/clang_format.sh
